### ISSUE TITLE
[ ISSUE ] TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by batarabagus** [deadlinecode/baileys-bottle#18]
**Describe the bug**
`if (pack || arguments.length === 2) for (var i = 0, l = from.length, ar; i < l; i++)` at ../baileys-bottle/lib/DB.js:50 
`                                                              ^                       `
TypeError: Cannot read properties of undefined (reading 'length') 

**To Reproduce**
1. Go to 'use baileys-bottle version 2.1.0 and up'

**Expected behavior**
Create store using MySQL as database successfully.

**Screenshots**
![error](https://user-images.githubusercontent.com/86773728/227608338-464fa2c4-da06-4d63-8a43-505fc4431d7d.png)

**Version (please complete the following information):**
 - NodeJS: 18.13.0
 - Baileys edge version

**Additional context**
Currently using baileys-bottle version 2.0.0 which runs normally.

**Comment by deadlinecode** [comment]
Will fix asap

**Comment by deadlinecode** [comment]
@batarabagus fixed in the latest release 2.1.2
