### ISSUE TITLE
[ ISSUE ] driverError: Error: ER_NO_DEFAULT_FOR_FIELD: Field 'id' doesn't have a default value

### ISSUE THREAD

**Issue by morganzysman** [deadlinecode/baileys-bottle#3]
**Describe the bug**
Hi, I'm trying to connect using an MYSQL DB.
When scanning the QR code I get this error
**To Reproduce**
1. Scan a connection QR

**Screenshots**

**Version (please complete the following information):**
 - NodeJS: [16.11.0]
 - Baileys [4.3.0]
 - Others...

**Comment by morganzysman** [comment]
<img width="937" alt="Screen Shot 2022-08-29 at 13 00 03" src="https://user-images.githubusercontent.com/5576762/187267587-87f87e68-e372-4985-b17f-70f9a67bb83f.png">

**Comment by morganzysman** [comment]
After setting auto increment to true I get the new error
<img width="953" alt="Screen Shot 2022-08-29 at 13 03 16" src="https://user-images.githubusercontent.com/5576762/187268225-4287f6eb-9910-456d-9d57-114a2e388522.png">

**Comment by h110m** [comment]
Ig we need to find another data type for mysql since the one provided doesn't let us store enough chars
Will look into it soon

**Comment by h110m** [comment]
Oh and @morganzysman 
Also please update to the newest Version of baileys bottle since we are now using baileys@4.4.0

**Comment by morganzysman** [comment]
> Ig we need to find another data type for mysql since the one provided doesn't let us store enough chars Will look into it soon

Hi, Thanks.

I changed the data type to text and setted up auto increment for this to work

**Comment by deadlinecode** [comment]
All MySQL problems will be tracked in #9
