### ISSUE TITLE
[ ISSUE ] Scanning QR creates multiple auth records

### ISSUE THREAD

**Issue by morganzysman** [deadlinecode/baileys-bottle#4]
**Describe the bug**
When i scan de QR code i get 17 auth token using MYSQL

**Expected behavior**
One sessions

**Screenshots**
<img width="1077" alt="Screen Shot 2022-08-29 at 13 05 49" src="https://user-images.githubusercontent.com/5576762/187268852-7388d0c7-d085-4d9b-b5e2-2cc78d79b19e.png">

**Version (please complete the following information):**
 - NodeJS: [16.11.0]
 - Baileys [4.3.0]

**Comment by h110m** [comment]
Yes
I will try to fix this asap
Should be just a problem with how typeorm handles updating via the ˋsaveˋ method

**Comment by deadlinecode** [comment]
All MySQL problems will be tracked in #9
