### ISSUE TITLE
[ ISSUE ] Contact table doesn't exite

### ISSUE THREAD

**Issue by morganzysman** [deadlinecode/baileys-bottle#6]
Hi,

When I bind the store i get the folowwing issue.
Auth table was created without an issue but it is the only one.

<img width="944" alt="Screen Shot 2022-08-29 at 13 49 16" src="https://user-images.githubusercontent.com/5576762/187275967-5ba9717e-06f7-4844-b147-b65fb70704ff.png">

Regards

**Comment by h110m** [comment]
Could you please share your db config (the options object passed to baileys bottle without any auth info ofc)

**Comment by morganzysman** [comment]
Hi,

Config attached

**Comment by morganzysman** [comment]
<img width="412" alt="Screen Shot 2022-08-30 at 19 11 22" src="https://user-images.githubusercontent.com/5576762/187565271-3fbe6d95-c4b5-48b1-9c80-96b653c21ea4.png">

**Comment by deadlinecode** [comment]
Same as #7 
Closing and continuing discussion on #7
