### ISSUE TITLE
can i use this for production?

### ISSUE THREAD

**Issue by ahmedRSA** [deadlinecode/baileys-bottle#8]
is this library dead because i dont see any development in it **(no commits, no active PRs)**
i want to use it for production but i see some issues opened and they dont have any activity in them seems 
seems like developer is no longer maintaining this repository.

**Comment by ahmedRSA** [comment]
ignore my english/grammer

**Comment by h110m** [comment]
Yes it is still maintained
I don't currently have the time to test every DB
As soon as im able too i will add it to the tested db's

You can still use it in production
If you run into errors just post them here and i will try to solve them asap
(and don't worry bout your english mine is also bad xD)
